opt_in_rules: all
analyzer_rules: all

disabled_rules:
    - anyobject_protocol
    - conditional_returns_on_newline
    - contrasted_opening_brace
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - explicit_acl
    - explicit_self
    - explicit_top_level_acl
    - inert_defer
    - nesting
    - no_magic_numbers
    - prefixed_toplevel_constant
    - required_deinit
    - sorted_enum_cases
    - switch_case_on_newline
    - unused_capture_list
    - unused_declaration
    - vertical_whitespace_between_cases
    - vertical_whitespace_opening_braces

cyclomatic_complexity:
    ignores_case_statements: true
deployment_target:
    macOS_deployment_target: 14.0
explicit_init:
    include_bare_init: true
explicit_type_interface:
    allow_redundancy: true
identifier_name:
    min_length: 2
indentation_width:
    include_comments: false
large_tuple: 3
line_length: 128
multiline_arguments:
    first_argument_location: next_line
number_separator:
    minimum_length: 6
operator_usage_whitespace:
    lines_look_around: 399
    skip_aligned_constants: false
prefer_key_path:
    restrict_to_standard_functions: false
private_over_fileprivate:
    validate_extensions: true
redundant_type_annotation:
    consider_default_literal_types_redundant: true
trailing_comma:
    mandatory_comma: true
trailing_whitespace:
    ignores_comments: false
type_name:
    min_length: 2
unused_import:
    require_explicit_imports: true
