strict: true

opt_in_rules: all

disabled_rules:
  - conditional_returns_on_newline
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - explicit_acl
  - explicit_top_level_acl
  - let_var_whitespace
  - no_magic_numbers
  - required_deinit
  - sorted_enum_cases
  - switch_case_on_newline
  - type_contents_order
  - vertical_whitespace_opening_braces

cyclomatic_complexity:
  ignores_case_statements: true
explicit_type_interface:
  allow_redundancy: true
identifier_name:
  min_length: 2
line_length: 256
nesting:
  type_level: 3
trailing_whitespace:
  ignores_comments: false
type_name:
  min_length: 2
