lenient: true
opt_in_rules: all
analyzer_rules: all

disabled_rules:
    - closure_body_length
    - conditional_returns_on_newline
    - contrasted_opening_brace
    - discouraged_none_name
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - explicit_acl
    - explicit_self
    - explicit_top_level_acl
    - function_default_parameter_at_end
    - nesting
    - no_magic_numbers
    - nslocalizedstring_key
    - nslocalizedstring_require_bundle
    - prefixed_toplevel_constant
    - required_deinit
    - sorted_enum_cases
    - switch_case_on_newline
    - trailing_closure
    - vertical_whitespace_between_cases
    - vertical_whitespace_opening_braces

cyclomatic_complexity:
    ignores_case_statements: true
deployment_target:
    macOS_deployment_target: 15.0
explicit_init:
    include_bare_init: true
explicit_type_interface:
    allow_redundancy: true
file_name:
    excluded:
        - Array.swift
identifier_name:
    min_length: 2
indentation_width:
    include_comments: false
large_tuple: 3
line_length: 128
multiline_arguments:
    first_argument_location: next_line
number_separator:
    minimum_length: 6
operator_usage_whitespace:
    lines_look_around: 399
    skip_aligned_constants: false
prefer_key_path:
    restrict_to_standard_functions: false
private_over_fileprivate:
    validate_extensions: true
redundant_type_annotation:
    consider_default_literal_types_redundant: true
switch_case_alignment:
    indented_cases: true
trailing_comma:
    mandatory_comma: true
trailing_whitespace:
    ignores_comments: false
type_contents_order:
    order:
        - case
        - type_alias
        - associated_type
        - [subtype, type_property]
        - instance_property
        - initializer
        - deinitializer
        - type_method
        - view_life_cycle_method
        - other_method
        - subscript
type_name:
    min_length: 2
unused_declaration:
    include_public_and_open: true
unused_import:
    require_explicit_imports: true
