#
# © 2024 F1248 <f1248@mailbox.org>
# See LICENSE.txt for license information.
#

lenient: true
opt_in_rules: all
analyzer_rules: all

disabled_rules:
    - closure_body_length
    - conditional_returns_on_newline
    - contrasted_opening_brace
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - explicit_acl
    - explicit_self
    - explicit_top_level_acl
    - function_default_parameter_at_end
    - multiple_closures_with_trailing_closure
    - nesting
    - no_magic_numbers
    - prefixed_toplevel_constant
    - private_swiftui_state
    - required_deinit
    - sorted_enum_cases
    - switch_case_on_newline
    - vertical_whitespace_opening_braces

cyclomatic_complexity:
    ignores_case_statements: true
deployment_target:
    macOS_deployment_target: 13.0
explicit_init:
    include_bare_init: true
explicit_type_interface:
    allow_redundancy: true
file_name:
    excluded:
        - Array.swift
    require_fully_qualified_names: true
identifier_name:
    min_length: 2
indentation_width:
    include_comments: false
large_tuple: 2
line_length: 128
multiline_arguments:
    first_argument_location: next_line
multiline_call_arguments:
    max_number_of_single_line_parameters: 3
multiline_parameters:
    max_number_of_single_line_parameters: 2
no_empty_block:
    disabled_block_types:
        - closure_blocks
non_optional_string_data_conversion:
    include_variables: true
number_separator:
    minimum_length: 6
opening_brace:
    ignore_multiline_statement_conditions: true
operator_usage_whitespace:
    lines_look_around: 399
    skip_aligned_constants: false
prefer_key_path:
    restrict_to_standard_functions: false
private_over_fileprivate:
    validate_extensions: true
redundant_self:
    keep_in_initializers: true
    only_in_closures: false
switch_case_alignment:
    indented_cases: true
trailing_closure:
    only_single_muted_parameter: true
trailing_comma:
    mandatory_comma: true
trailing_whitespace:
    ignores_comments: false
type_body_length:
    excluded_types: []
type_contents_order:
    order:
        - case
        - type_alias
        - associated_type
        - [subtype, type_property]
        - instance_property
        - initializer
        - deinitializer
        - type_method
        - view_life_cycle_method
        - other_method
        - subscript
type_name:
    min_length: 2
unused_declaration:
    include_public_and_open: true
unused_import:
    require_explicit_imports: true
vertical_whitespace_between_cases:
    separation: never
