opt_in_rules: all

disabled_rules:
    - anyobject_protocol
    - conditional_returns_on_newline
    - contrasted_opening_brace
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - explicit_acl
    - explicit_top_level_acl
    - inert_defer
    - nesting
    - no_magic_numbers
    - nslocalizedstring_key
    - nslocalizedstring_require_bundle
    - prefixed_toplevel_constant
    - required_deinit
    - sorted_enum_cases
    - switch_case_on_newline
    - unused_capture_list
    - vertical_whitespace_between_cases
    - vertical_whitespace_opening_braces

cyclomatic_complexity:
    ignores_case_statements: true
explicit_type_interface:
    allow_redundancy: true
identifier_name:
    min_length: 2
indentation_width:
    include_comments: false
large_tuple: 3
line_length: 128
trailing_comma:
    mandatory_comma: true
trailing_whitespace:
    ignores_comments: false
type_name:
    min_length: 2
