#!/bin/sh

#
# © 2024 F1248 <f1248@mailbox.org>
# See LICENSE.txt for license information.
#

PATH=/usr/bin:/bin
set -o errexit
set -o nounset

if ! { [ -f /usr/bin/uname ] && [ -x /usr/bin/uname ] && [ "$(uname)" = "Darwin" ]; }; then
	printf "\nError: Genius requires macOS!\n" >&2
	exit 1
fi

if ! { [ -n "${BASH_VERSION-}" ] && [ -n "${POSIXLY_CORRECT-}" ]; }; then
	printf "\nError: Installation script must be executed with \`sh\`!\n" >&2
	exit 1
fi

set -o pipefail
set -o privileged

note() {
	echo "\nNote: $1\n"
}

fail() {
	echo "\nError: $1\n" >&2
	exit 1
}

is_recoveryos=$([[ ! -e /System/Library/CoreServices/Finder.app ]] && echo true || echo false)

if $is_recoveryos; then
	if ! (( $(sw_vers -productVersion | cut -d "." -f 1) >= 14 )); then
		fail "Genius requires macOS Sonoma 14 or later in recoveryOS!"
	fi
	note "Genius only remains installed until restarting."
else
	if ! (( $(sw_vers -productVersion | cut -d "." -f 1) >= 13 )); then
		fail "Genius requires macOS Ventura 13 or later!"
	fi
fi

echo "\nPreparing..."
if [[ -w /Applications ]]; then
	cd /Applications
else
	mkdir -p ~/Applications
	cd ~/Applications
fi
if [[ -e Genius.zip ]]; then
	fail "Genius.zip already exists in $PWD"
fi
if [[
	-e Genius.app && (
		! -f Genius.app/Contents/Info.plist ||
			$(defaults read "$PWD/Genius.app/Contents/Info.plist" "CFBundleIdentifier") != "dev.F1248.Genius"
	)
]]; then
	fail "A different app already exists at $PWD/Genius.app!"
fi

echo "Quitting Genius..."
if $is_recoveryos; then
	killall -q Genius || true
else
	for _ in $(pgrep -x Genius); do
		osascript -e "quit app \"Genius\""
	done
fi

echo "Downloading..."
curl --no-progress-meter download-url --location --remote-name

echo "Installing..."
rm -r -f Genius.app
unzip -q -o Genius.zip
if [[ ! -d Genius.app ]]; then
	unzip -q Genius.zip
fi

if $is_recoveryos; then
	echo "Creating alias..."
	echo "\nalias genius=\"$PWD/Genius.app/Contents/MacOS/Genius &> /dev/null\"" >> ~/.bash_profile
fi

echo "Cleaning up..."
rm Genius.zip

echo "Opening..."
if $is_recoveryos; then
	Genius.app/Contents/MacOS/Genius &> /dev/null
	note "To reopen Genius run \`genius\` in a new shell."
else
	open Genius.app
	sleep 0.5
	open Genius.app # work around `open` opening apps in the background when not already running
fi

echo "Done."
