#!/bin/bash

#
# © 2025 F1248 <f1248@mailbox.org>
# See LICENSE.txt for license information.
#

PATH="/usr/bin:/bin"
set -e

if [[ $0 != */Genius.app/Contents/Resources/Uninstall ]]; then
	exit 1
fi

cd "$(dirname "$0")"/../../..

while ps aux -c | grep -w Genius > /dev/null; do
	sleep 0.1
done

set +e

rm -r -f Genius.app
rm -r -f ~/Library/Caches/dev.F1248.Genius
rm -r -f /Users/*/Library/Caches/dev.F1248.Genius
rm -r -f ~/Library/HTTPStorages/dev.F1248.Genius
rm -r -f /Users/*/Library/HTTPStorages/dev.F1248.Genius
defaults delete ~/Library/Preferences/dev.F1248.Genius.plist
defaults delete /Users/*/Library/Preferences/dev.F1248.Genius.plist
rm -f ~/Library/Preferences/dev.F1248.Genius.plist
rm -f /Users/*/Library/Preferences/dev.F1248.Genius.plist
