#
# © 2024 F1248 <f1248@mailbox.org>
# See LICENSE.txt for license information.
#

name: Trigger Deploy to GitHub Pages

on:
    create:
    delete:
    push:
        paths:
            - .github/workflows/Trigger-Deploy-to-GitHub-Pages.yml
            - Install
    release:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions: {}

jobs:
    Trigger-Deploy-to-GitHub-Pages:
        name: Trigger Deploy to GitHub Pages
        runs-on: ubuntu-latest

        steps:
            - name: Trigger Deploy to GitHub Pages
              uses: actions/github-script@main
              with:
                github-token: ${{ secrets.TRIGGER_DEPLOY_TO_GITHUB_PAGES_TOKEN }}
                script: |
                    await github.rest.actions.createWorkflowDispatch({
                        owner: "F1248",
                        repo: "f1248.github.io",
                        workflow_id: "Deploy-to-GitHub-Pages.yml",
                        ref: "main",
                    });
